name: CI/CD to Minikube
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn clean package
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build Docker Image
      run: docker build -t java-todo-app .
    - name: Deploy Info
      run: echo "Manual deployment to Minikube required after build"